# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  config.vm.box = "ubuntu/trusty32"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.boot_timeout = 1000
  #config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  #   v.memory = 2048
  #   v.cpus = 2
  #end 	
  config.vm.network "private_network", ip: "10.11.12.11"
  config.vm.hostname = "myvm14"
  config.vm.network :forwarded_port, guest: 22, host: 2221, id: "ssh", auto_correct: true
end
