# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  config.vm.box = "centos/7"
  #config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.boot_timeout = 1000
  #config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  #   v.memory = 2048
  #   v.cpus = 2
  #end 	
  config.vm.network "private_network", ip: "10.11.12.10"
  config.vm.hostname = "mycentos7"
  config.vm.network :forwarded_port, guest: 22, host: 2220, id: "ssh", auto_correct: true
  config.vm.synced_folder "./", "/vagrant", type: "virtualbox", disabled: false

  # config.vm.box_check_update = false
  # config.vm.synced_folder "../data", "/vagrant_data"
end
